using NUnit.Framework;

namespace Assignment1.UnitTest
{
    public class Assignment1Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void Test1()
            
        {
            Assert.Pass();
            AutoGeneratedProgram
        }
    }
}
